all: \
	mainString.class\
	StringCalculator.class \

mainString.class: mainString.java
	javac mainString.java

StringCalculator.class: StringCalculator.java
	javac StringCalculator.java

clean: 
	$(RM) *.class